export const transactions = [
  {
    id: 1,
    type: 'income',
    category: 'salary',
    amount: 2850,
    description: 'Software Engineer salary',
    date: '2024-12-01',
  },
  {
    id: 2,
    type: 'expense',
    category: 'rent',
    amount: 1200,
    description: 'Apartment rent December',
    date: '2024-12-05',
  },
  {
    id: 3,
    type: 'expense',
    category: 'groceries',
    amount: 87.45,
    description: 'Albert Heijn shopping',
    date: '2024-12-08',
  },
  {
    id: 4,
    type: 'expense',
    category: 'transportation',
    amount: 45.50,
    description: 'NS train subscription',
    date: '2024-12-10',
  },
  {
    id: 5,
    type: 'expense',
    category: 'entertainment',
    amount: 32.90,
    description: 'Netflix & Spotify',
    date: '2024-12-12',
  },
  {
    id: 6,
    type: 'income',
    category: 'freelance',
    amount: 450,
    description: 'Website redesign project',
    date: '2024-12-15',
  },
  {
    id: 7,
    type: 'expense',
    category: 'groceries',
    amount: 112.30,
    description: 'Jumbo weekly shopping',
    date: '2024-12-18',
  },
  {
    id: 8,
    type: 'expense',
    category: 'utilities',
    amount: 156.20,
    description: 'Electricity & water bill',
    date: '2024-12-20',
  },
  {
    id: 9,
    type: 'expense',
    category: 'entertainment',
    amount: 48.75,
    description: 'Dinner at restaurant',
    date: '2024-12-22',
  },
  {
    id: 10,
    type: 'expense',
    category: 'shopping',
    amount: 89.99,
    description: 'Winter jacket',
    date: '2024-12-28',
  },
  {
    id: 11,
    type: 'income',
    category: 'salary',
    amount: 2850,
    description: 'Software Engineer salary',
    date: '2025-01-01',
  },
  {
    id: 12,
    type: 'expense',
    category: 'rent',
    amount: 1200,
    description: 'Apartment rent January',
    date: '2025-01-05',
  },
  {
    id: 13,
    type: 'expense',
    category: 'groceries',
    amount: 95.60,
    description: 'Aldi shopping',
    date: '2025-01-09',
  },
  {
    id: 14,
    type: 'expense',
    category: 'healthcare',
    amount: 128.50,
    description: 'Health insurance premium',
    date: '2025-01-12',
  },
  {
    id: 15,
    type: 'income',
    category: 'freelance',
    amount: 320,
    description: 'Logo design work',
    date: '2025-01-15',
  },
  {
    id: 16,
    type: 'expense',
    category: 'groceries',
    amount: 78.20,
    description: 'Albert Heijn shopping',
    date: '2025-01-18',
  },
  {
    id: 17,
    type: 'expense',
    category: 'transportation',
    amount: 45.50,
    description: 'NS train subscription',
    date: '2025-01-20',
  },
  {
    id: 18,
    type: 'expense',
    category: 'entertainment',
    amount: 65.00,
    description: 'Concert tickets',
    date: '2025-01-25',
  },
  {
    id: 19,
    type: 'expense',
    category: 'utilities',
    amount: 142.80,
    description: 'Internet & mobile phone',
    date: '2025-01-28',
  },
  {
    id: 20,
    type: 'income',
    category: 'salary',
    amount: 2850,
    description: 'Software Engineer salary',
    date: '2025-02-01',
  },
];